In [1]:
import pandas as pd
import numpy as np

In [4]:
# read Orders sheet from the input file
df=pd.read_excel('Input_Sample - Superstore.xls',sheet_name='Orders')

In [7]:
df.shape

(9994, 21)

In [10]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State                     object
Postal Code              float64
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [12]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [14]:
# add order year 
df['year']=df['Order Date'].dt.year 
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,year
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2020
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2020
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2020
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2019
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2019

In [53]:
# find the first purchase year for each custom
# Here a cohort means a group that share the same 'first-purchase-year'
s=df.groupby(by='Customer Name').year.min()
s.values[0:10]

array([2018, 2018, 2018, 2019, 2018, 2018, 2018, 2018, 2020, 2018],
      dtype=int64)

In [54]:
# create dataframe contain all custom names with ID
df_name=df.loc[:,['Customer ID', 'Customer Name']]
df_name.drop_duplicates(inplace=True, ignore_index=True)
df_name['key']=0
df_name.sort_values(by='Customer Name',inplace=True, ignore_index=True)
df_name['First Purchase Date']=s.values
df_name

    Customer ID       Customer Name  key  First Purchase Date
0      AB-10015       Aaron Bergman    0                 2018
1      AH-10030       Aaron Hawkins    0                 2018
2      AS-10045      Aaron Smayling    0                 2018
3      AB-10060     Adam Bellavance    0                 2019
4      AH-10075           Adam Hart    0                 2018
..          ...                 ...  ...                  ...
788    XP-21865        Xylona Preis    0                 2018
789    YS-21880       Yana Sorensen    0                 2019
790    YC-21895      Yoseph Carroll    0                 2018
791    ZC-21910    Zuschuss Carroll    0                 2018
792    ZD-21925  Zuschuss Donatelli    0                 2018

[793 rows x 4 columns]

In [32]:
# create dataframe with year as column
df_year=pd.DataFrame([[0,2018],[0,2019],[0,2020] ,[0,2021]], columns=['key','Year'])
df_year

   key  Year
0    0  2018
1    0  2019
2    0  2020
3    0  2021

In [55]:
# join df_name with df_year so that each custom includes a year duration from 2018-2021
df_temp=df_name.merge(df_year, on='key', how='left')
df_temp.drop(columns='key',inplace=True)
df_temp.head()

  Customer ID  Customer Name  First Purchase Date  Year
0    AB-10015  Aaron Bergman                 2018  2018
1    AB-10015  Aaron Bergman                 2018  2019
2    AB-10015  Aaron Bergman                 2018  2020
3    AB-10015  Aaron Bergman                 2018  2021
4    AH-10030  Aaron Hawkins                 2018  2018

In [57]:
# join df_temp with df so that each custom info contains a year from 2018-2021 if there is no order in a year, then NAN
df_final=df.merge(df_temp, left_on=['Customer ID','Customer Name','year'], right_on=['Customer ID','Customer Name','Year'], how='right')

In [ ]:
# drop column year
df_final.drop(columns='year',inplace=True)

In [62]:
df_final.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year
0,4962.0,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1.0,0.2,5.4801,2018,2018
1,4963.0,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,OFF-AR-10001427,Office Supplies,Art,Newell 330,17.940,3.0,0.0,4.6644,2018,2018
2,4964.0,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,OFF-ST-10002344,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3.0,0.0,4.8588,2018,2018
3,8223.0,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.624,2.0,0.2,-2.5248,2018,2018
4,NaN,NaN,NaT,NaT,NaN,AB-10015,Aaron Bergman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,2019
5,8802.0,CA-2020-140935,2020-11-10,2020-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,TEC-PH-10000562,Technology,Phones,Samsung Convoy 3,221.980,2.0,0.0,62.1544,2018,2020
6,8803.0,CA-2020-140935,2020-11-10,2020-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2.0,0.0,54.7136,2018,2020
7,NaN,NaN,NaT,NaT,NaN,AB-10015,Aaron Bergman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,2021
8,5355.0,CA-2018-113768,2018-05-13,2018-05-19,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Los Angeles,...,FUR-CH-10002439,Furniture,Chairs,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,0.2,20.9592,2018,2018
9,5356.0,CA-2018-113768,2018-05-13,2018-05-19,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Los Angeles,...,OFF-PA-10003063,Office Supplies,Paper,EcoTones Memo Sheets,8.000,2.0,0.0,3.8400,2018,2018

In [68]:
# find  rows that having initial date <= Year
index=df_final['First Purchase Date']<=df_final['Year']

In [79]:
# new dataframe only contains these index-rows
df_final1=df_final[index]
df_final1.shape

(10396, 23)

In [83]:
#Convert columns to best possible dtypes using dtypes supporting pd.NA.
df_final1=df_final1.convert_dtypes()

In [91]:
# add column order? if a custom has made an order this year, its value is 1 otherwise 0
df_final1['Order?']=df_final1['Sales'].notna().astype(int)

In [92]:
df_final1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year,Order?
0,4962,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,2018,2018,1
1,4963,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Office Supplies,Art,Newell 330,17.94,3,0.0,4.6644,2018,2018,1
2,4964,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.94,3,0.0,4.8588,2018,2018,1
3,8223,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,Office Supplies,Storage,Akro Stacking Bins,12.624,2,0.2,-2.5248,2018,2018,1
4,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0

In [100]:
# -- add column 'Last Year Order?'
# Generate a new dataframe S
S=df_final1.loc[:,['Customer Name','Year','Order?']].drop_duplicates()
S

            Customer Name  Year  Order?
0           Aaron Bergman  2018       1
4           Aaron Bergman  2019       0
5           Aaron Bergman  2020       1
7           Aaron Bergman  2021       0
8           Aaron Hawkins  2018       1
...                   ...   ...     ...
10649    Zuschuss Carroll  2021       1
10657  Zuschuss Donatelli  2018       1
10660  Zuschuss Donatelli  2019       0
10661  Zuschuss Donatelli  2020       1
10666  Zuschuss Donatelli  2021       1

[2901 rows x 3 columns]

In [109]:
# -- add column 'Last Year Order?' to S
S['Last Year Order?']=S.groupby(by='Customer Name').shift(periods=1).convert_dtypes()['Order?']
S.drop(columns='Order?',inplace=True)
S

            Customer Name  Year  Last Year Order?
0           Aaron Bergman  2018              <NA>
4           Aaron Bergman  2019                 1
5           Aaron Bergman  2020                 0
7           Aaron Bergman  2021                 1
8           Aaron Hawkins  2018              <NA>
...                   ...   ...               ...
10649    Zuschuss Carroll  2021                 1
10657  Zuschuss Donatelli  2018              <NA>
10660  Zuschuss Donatelli  2019                 1
10661  Zuschuss Donatelli  2020                 0
10666  Zuschuss Donatelli  2021                 1

[2901 rows x 3 columns]

In [112]:
#add 'last year order' to df_final1
df_final1=df_final1.merge(S, on=['Customer Name','Year'])

In [113]:
# -- calculate Customer Classification
# new
df_final1.loc[df_final1['First Purchase Date']==df_final1['Year'],'Customer Classification']='New'
df_final1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year,Order?,Customer Classification,Last Year Order?
0,4962,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,2018,2018,1,New,<NA>
1,4963,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Newell 330,17.94,3,0.0,4.6644,2018,2018,1,New,<NA>
2,4964,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Carina 42""Hx23 3/4""W Media Storage Unit",242.94,3,0.0,4.8588,2018,2018,1,New,<NA>
3,8223,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,Akro Stacking Bins,12.624,2,0.2,-2.5248,2018,2018,1,New,<NA>
4,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0,Sleeping,1

In [114]:
# Sleeping
df_final1.loc[df_final1['Order?']==0,'Customer Classification']='Sleeping'
df_final1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year,Order?,Customer Classification,Last Year Order?
0,4962,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,2018,2018,1,New,<NA>
1,4963,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Newell 330,17.94,3,0.0,4.6644,2018,2018,1,New,<NA>
2,4964,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Carina 42""Hx23 3/4""W Media Storage Unit",242.94,3,0.0,4.8588,2018,2018,1,New,<NA>
3,8223,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,Akro Stacking Bins,12.624,2,0.2,-2.5248,2018,2018,1,New,<NA>
4,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0,Sleeping,1

In [126]:
# consistent
df_final1.loc[(df_final1['Last Year Order?']==1) & (df_final1['Order?']==1),'Customer Classification']='Consistent'

In [127]:
pd.options.display.max_rows=None

In [135]:
df_final1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year,Order?,Customer Classification,Last Year Order?
0,4962,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,2018,2018,1,New,<NA>
1,4963,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Newell 330,17.94,3,0.0,4.6644,2018,2018,1,New,<NA>
2,4964,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Carina 42""Hx23 3/4""W Media Storage Unit",242.94,3,0.0,4.8588,2018,2018,1,New,<NA>
3,8223,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,Akro Stacking Bins,12.624,2,0.2,-2.5248,2018,2018,1,New,<NA>
4,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0,Sleeping,1

In [131]:
# Returning
df_final1.loc[(df_final1['Last Year Order?']==0) & (df_final1['Order?']==1),'Customer Classification']='Returning'
# check if 'Customer Classification' has null 
df_final1['Customer Classification'].isna().any()

False

In [134]:
df_final1.head(40)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,First Purchase Date,Year,Order?,Customer Classification,Last Year Order?
0,4962,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,2018,2018,1,New,<NA>
1,4963,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,Newell 330,17.94,3,0.0,4.6644,2018,2018,1,New,<NA>
2,4964,CA-2018-156587,2018-03-07,2018-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,"Carina 42""Hx23 3/4""W Media Storage Unit",242.94,3,0.0,4.8588,2018,2018,1,New,<NA>
3,8223,CA-2018-152905,2018-02-18,2018-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,Akro Stacking Bins,12.624,2,0.2,-2.5248,2018,2018,1,New,<NA>
4,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0,Sleeping,1
5,8802,CA-2020-140935,2020-11-10,2020-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,Samsung Convoy 3,221.98,2,0.0,62.1544,2018,2020,1,Returning,0
6,8803,CA-2020-140935,2020-11-10,2020-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,"Sauder Facets Collection Library, Sky Alder Fi...",341.96,2,0.0,54.7136,2018,2020,1,Returning,0
7,<NA>,<NA>,NaT,NaT,<NA>,AB-10015,Aaron Bergman,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2021,0,Sleeping,1
8,5355,CA-2018-113768,2018-05-13,2018-05-19,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Los Angeles,...,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6,0.2,20.9592,2018,2018,1,New,<NA>
9,5356,CA-2018-113768,2018-05-13,2018-05-19,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Los Angeles,...,EcoTones Memo Sheets,8.0,2,0.0,3.84,2018,2018,1,New,<NA>
10,6129,US-2018-158400,2018-10-25,2018-10-28,First Class,AH-10030,Aaron Hawkins,Corporate,United States,San Francisco,...,GBC VeloBind Cover Sets,49.408,4,0.2,18.528,2018,2018,1,New,<NA>
11,7164,CA-2018-122070,2018-04-22,2018-04-24,Second Class,AH-10030,Aaron Hawkins,Corporate,United States,Troy,...,Staple envelope,247.84,8,0.0,121.4416,2018,2018,1,New,<NA>
12,7165,CA-2018-122070,2018-04-22,2018-04-24,Second Class,AH-10030,Aaron Hawkins,Corporate,United States,Troy,...,"ACCOHIDE 3-Ring Binder, Blue, 1""",9.912,3,0.2,3.3453,2018,2018,1,New,<NA>
13,8804,CA-2018-157644,2018-12-31,2019-01-01,First Class,AH-10030,Aaron Hawkins,Corporate,United States,New York City,...,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,34.77,3,0.0,11.4741,2018,2018,1,New,<NA>
14,8805,CA-2018-157644,2018-12-31,2019-01-01,First Class,AH-10030,Aaron Hawkins,Corporate,United States,New York City,...,Avery 51,18.9,3,0.0,8.694,2018,2018,1,New,<NA>
15,9680,CA-2019-130113,2019-12-27,2019-12-31,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,San Francisco,...,Fellowes Super Stor/Drawer Files,323.1,2,0.0,61.389,2018,2019,1,Consistent,1
16,9681,CA-2019-130113,2019-12-27,2019-12-31,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,San Francisco,...,Geemarc AmpliPOWER60,668.16,9,0.2,75.168,2018,2019,1,Consistent,1
17,3312,CA-2020-162747,2020-03-20,2020-03-25,Second Class,AH-10030,Aaron Hawkins,Corporate,United States,Gulfport,...,"Eldon Image Series Desk Accessories, Ebony",86.45,7,0.0,38.038,2018,2020,1,Consistent,1
18,3200,CA-2021-164000,2021-12-18,2021-12-22,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Philadelphia,...,Avery Fluorescent Highlighter Four-Color Set,18.704,7,0.2,2.338,2018,2021,1,Consistent,1
19,4580,US-2018-150126,2018-07-27,2018-08-02,Standard Class,AS-10045,Aaron Smayling,Corporate,United States,New York City,...,Xerox 1956,65.78,11,0.0,32.2322,2018,2018,1,New,<NA>
20,<NA>,<NA>,NaT,NaT,<NA>,AS-10045,Aaron Smayling,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,2018,2019,0,Sleeping,1
21,1352,CA-2020-162901,2020-03-28,2020-03-31,First Class,AS-10045,Aaron Smayling,Corporate,United States,Arlington,...,Hanging Personal Folder File,31.4,2,0.0,7.85,2018,2020,1,Returning,0
22,9538,CA-2020-148747,2020-09-25,2020-09-27,First Class,AS-10045,Aaron Smayling,Corporate,United States,San Francisco,...,"Atlantic Metals Mobile 4-Shelf Bookcases, Cust...",477.666,2,0.15,84.294,2018,2020,1,Returning,0
23,1341,CA-2021-113481,2021-01-02,2021-01-04,First Class,AS-10045,Aaron Smayling,Corporate,United States,Jacksonville,...,Cisco CP-7937G Unified IP Conference Station P...,695.7,2,0.5,-27.828,2018,2021,1,Consistent,1
24,1342,CA-2021-113481,2021-01-02,2021-01-04,First Class,AS-10045,Aaron Smayling,Corporate,United States,Jacksonville,...,"Avery 3 1/2"" Diskette Storage Pages, 10/Pack",15.66,5,0.7,-12.528,2018,2021,1,Consistent,1
25,1343,CA-2021-113481,2021-01-02,2021-01-04,First Class,AS-10045,Aaron Smayling,Corporate,United States,Jacksonville,...,Avery Recycled Flexi-View Covers for Binding S...,28.854,6,0.7,-21.1596,2018,2021,1,Consistent,1
26,1834,CA-2021-162691,2021-08-01,2021-08-07,Standard Class,AS-10045,Aaron Smayling,Corporate,United States,Austin,...,Bady BDG101FRU Card Printer,1439.982,3,0.4,-263.9967,2018,2021,1,Consistent,1
27,1835,CA-2021-162691,2021-08-01,2021-08-07,Standard Class,AS-10045,Aaron Smayling,Corporate,United States,Austin,...,Xerox 1998,36.288,7,0.2,12.7008,2018,2021,1,Consistent,1
28,3040,CA-2021-101749,2021-10-03,2021-10-08,Standard Class,AS-10045,Aaron Smayling,Corporate,United States,Pasadena,...,"Lesro Sheffield Collection Coffee Table, End T...",171.288,3,0.2,-6.4233,2018,2021,1,Consistent,1
29,9129,US-2021-147655,2021-09-04,2021-09-05,First Class,AS-10045,Aaron Smayling,Corporate,United States,Redmond,...,"Avery Trapezoid Extra Heavy Duty 4"" Binders",88.074,7,0.7,-58.716,2018,2021,1,Consistent,1
30,5051,CA-2019-150511,2019-09-18,2019-09-24,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Des Moines,...,"Wirebound Message Books, Four 2 3/4"" x 5"" Form...",18.54,2,0.0,8.7138,2019,2019,1,New,<NA>
31,350,CA-2020-129714,2020-09-01,2020-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,Sabrent 4-Port USB 2.0 Hub,6.79,1,0.0,2.3086,2019,2020,1,Consistent,1
32,351,CA-2020-129714,2020-09-01,2020-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,Xerox 1881,24.56,2,0.0,11.5432,2019,2020,1,Consistent,1
33,352,CA-2020-129714,2020-09-01,2020-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,Acco Hanging Data Binders,3.048,1,0.2,1.0668,2019,2020,1,Consistent,1
34,353,CA-2020-129714,2020-09-01,2020-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,Xerox 1881,49.12,4,0.0,23.0864,2019,2020,1,Consistent,1
35,354,CA-2020-129714,2020-09-01,2020-09-03,First Class,AB-10060,Adam Bellavance,Home Office,United States,New York City,...,GBC DocuBind P400 Electric Binding System,4355.168,4,0.2,1415.4296,2019,2020,1,Consistent,1
36,1176,CA-2020-161207,2020-08-29,2020-09-03,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Concord,...,Acme Forged Steel Scissors with Black Enamel H...,27.93,3,0.0,8.0997,2019,2020,1,Consistent,1
37,2364,US-2020-108637,2020-03-13,2020-03-18,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Waynesboro,...,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",127.88,2,0.0,40.9216,2019,2020,1,Consistent,1
38,2365,US-2020-108637,2020-03-13,2020-03-18,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Waynesboro,...,"Eureka The Boss Lite 10-Amp Upright Vacuum, Blue",160.32,2,0.0,44.8896,2019,2020,1,Consistent,1
39,2366,US-2020-108637,2020-03-13,2020-03-18,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Waynesboro,...,Ibico Covers for Plastic or Wire Binding Elements,46.0,4,0.0,20.7,2019,2020,1,Consistent,1

In [150]:
# calculate YoY Difference
# create df_unique to remove unnecessary and duplicated information from df_final1
df_unique=df_final1.loc[:,['Customer ID','Customer Name','First Purchase Date','Year','Order?','Last Year Order?','Customer Classification']]
df_unique.drop_duplicates(inplace=True)

In [151]:
df_unique.shape

(2901, 7)

In [159]:
# calculate number of active customers in 2018 with first_purchase_date=2018
Num_2018_2018=df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Customer Classification']=='New'),'Order?'].sum()
Num_2018_2018

595

In [162]:
# calculate number of active customers in 2019 with first_purchase_date=2018
Num_2018_2019=df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2019),'Order?'].sum()
Num_2018_2019

437

In [163]:
# calculate number of active customers in 2020 with first_purchase_date=2018
Num_2018_2020=df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2020),'Order?'].sum()
Num_2018_2020

485

In [164]:
# calculate number of active customers in 2021 with first_purchase_date=2018
Num_2018_2021=df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2021),'Order?'].sum()
Num_2018_2021

517

In [177]:
# calculate 'YoY Difference' for customers with first_purchase_date=2018
df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2019),'YoY Difference']=Num_2018_2019-Num_2018_2018
df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2020),'YoY Difference']=Num_2018_2020-Num_2018_2019
df_unique.loc[(df_unique['First Purchase Date']==2018)&(df_unique['Year']==2021),'YoY Difference']=Num_2018_2021-Num_2018_2020
df_unique.head()

,Customer ID,Customer Name,First Purchase Date,Year,Order?,Last Year Order?,Customer Classification,YoY Difference
0,AB-10015,Aaron Bergman,2018,2018,1,<NA>,New,NaN
4,AB-10015,Aaron Bergman,2018,2019,0,1,Sleeping,-158
5,AB-10015,Aaron Bergman,2018,2020,1,0,Returning,48
7,AB-10015,Aaron Bergman,2018,2021,0,1,Sleeping,32
8,AH-10030,Aaron Hawkins,2018,2018,1,<NA>,New,NaN

In [178]:
# calculate number of active customers in 2019 with first_purchase_date=2019
Num_2019_2019=df_unique.loc[(df_unique['First Purchase Date']==2019)&(df_unique['Customer Classification']=='New'),'Order?'].sum()
Num_2019_2019

136

In [179]:
# calculate number of active customers in 2020 with first_purchase_date=2019
Num_2019_2020=df_unique.loc[(df_unique['First Purchase Date']==2019)&(df_unique['Year']==2020),'Order?'].sum()
Num_2019_2020

102

In [180]:
# calculate number of active customers in 2021 with first_purchase_date=2019
Num_2019_2021=df_unique.loc[(df_unique['First Purchase Date']==2019)&(df_unique['Year']==2021),'Order?'].sum()
Num_2019_2021

120

In [182]:
# calculate 'YoY Difference' for customers with first_purchase_date=2019
df_unique.loc[(df_unique['First Purchase Date']==2019)&(df_unique['Year']==2020),'YoY Difference']=Num_2019_2020-Num_2019_2019
df_unique.loc[(df_unique['First Purchase Date']==2019)&(df_unique['Year']==2021),'YoY Difference']=Num_2019_2021-Num_2019_2020
df_unique.head(40)

,Customer ID,Customer Name,First Purchase Date,Year,Order?,Last Year Order?,Customer Classification,YoY Difference
0,AB-10015,Aaron Bergman,2018,2018,1,<NA>,New,NaN
4,AB-10015,Aaron Bergman,2018,2019,0,1,Sleeping,-158
5,AB-10015,Aaron Bergman,2018,2020,1,0,Returning,48
7,AB-10015,Aaron Bergman,2018,2021,0,1,Sleeping,32
8,AH-10030,Aaron Hawkins,2018,2018,1,<NA>,New,NaN
15,AH-10030,Aaron Hawkins,2018,2019,1,1,Consistent,-158
17,AH-10030,Aaron Hawkins,2018,2020,1,1,Consistent,48
18,AH-10030,Aaron Hawkins,2018,2021,1,1,Consistent,32
19,AS-10045,Aaron Smayling,2018,2018,1,<NA>,New,NaN
20,AS-10045,Aaron Smayling,2018,2019,0,1,Sleeping,-158
21,AS-10045,Aaron Smayling,2018,2020,1,0,Returning,48
23,AS-10045,Aaron Smayling,2018,2021,1,1,Consistent,32
30,AB-10060,Adam Bellavance,2019,2019,1,<NA>,New,NaN
31,AB-10060,Adam Bellavance,2019,2020,1,1,Consistent,-34
40,AB-10060,Adam Bellavance,2019,2021,1,1,Consistent,18
48,AH-10075,Adam Hart,2018,2018,1,<NA>,New,NaN
49,AH-10075,Adam Hart,2018,2019,1,1,Consistent,-158
50,AH-10075,Adam Hart,2018,2020,1,1,Consistent,48
56,AH-10075,Adam Hart,2018,2021,1,1,Consistent,32
68,AS-10090,Adam Shillingsburg,2018,2018,1,<NA>,New,NaN
73,AS-10090,Adam Shillingsburg,2018,2019,1,1,Consistent,-158
77,AS-10090,Adam Shillingsburg,2018,2020,1,1,Consistent,48
85,AS-10090,Adam Shillingsburg,2018,2021,1,1,Consistent,32
93,AB-10105,Adrian Barton,2018,2018,1,<NA>,New,NaN
95,AB-10105,Adrian Barton,2018,2019,1,1,Consistent,-158
101,AB-10105,Adrian Barton,2018,2020,1,1,Consistent,48
104,AB-10105,Adrian Barton,2018,2021,1,1,Consistent,32
113,AH-10120,Adrian Hane,2018,2018,1,<NA>,New,NaN
114,AH-10120,Adrian Hane,2018,2019,0,1,Sleeping,-158
115,AH-10120,Adrian Hane,2018,2020,1,0,Returning,48
123,AH-10120,Adrian Hane,2018,2021,1,1,Consistent,32
130,AS-10135,Adrian Shami,2020,2020,1,<NA>,New,NaN
131,AS-10135,Adrian Shami,2020,2021,1,1,Consistent,NaN
133,AB-10150,Aimee Bixby,2018,2018,1,<NA>,New,NaN
138,AB-10150,Aimee Bixby,2018,2019,1,1,Consistent,-158
139,AB-10150,Aimee Bixby,2018,2020,1,1,Consistent,48
140,AB-10150,Aimee Bixby,2018,2021,1,1,Consistent,32
145,AB-10165,Alan Barnes,2018,2018,1,<NA>,New,NaN
146,AB-10165,Alan Barnes,2018,2019,1,1,Consistent,-158
152,AB-10165,Alan Barnes,2018,2020,0,1,Sleeping,48

In [183]:
# calculate number of active customers in 2020 with first_purchase_date=2020
Num_2020_2020=df_unique.loc[(df_unique['First Purchase Date']==2020)&(df_unique['Year']==2020),'Order?'].sum()
Num_2020_2020

51

In [184]:
# calculate number of active customers in 2021 with first_purchase_date=2020
Num_2020_2021=df_unique.loc[(df_unique['First Purchase Date']==2020)&(df_unique['Year']==2021),'Order?'].sum()
Num_2020_2021

45

In [185]:
# calculate 'YoY Difference' for customers with first_purchase_date=2020
df_unique.loc[(df_unique['First Purchase Date']==2020)&(df_unique['Year']==2021),'YoY Difference']=Num_2020_2021-Num_2020_2020
df_unique.head(40)

,Customer ID,Customer Name,First Purchase Date,Year,Order?,Last Year Order?,Customer Classification,YoY Difference
0,AB-10015,Aaron Bergman,2018,2018,1,<NA>,New,NaN
4,AB-10015,Aaron Bergman,2018,2019,0,1,Sleeping,-158
5,AB-10015,Aaron Bergman,2018,2020,1,0,Returning,48
7,AB-10015,Aaron Bergman,2018,2021,0,1,Sleeping,32
8,AH-10030,Aaron Hawkins,2018,2018,1,<NA>,New,NaN
15,AH-10030,Aaron Hawkins,2018,2019,1,1,Consistent,-158
17,AH-10030,Aaron Hawkins,2018,2020,1,1,Consistent,48
18,AH-10030,Aaron Hawkins,2018,2021,1,1,Consistent,32
19,AS-10045,Aaron Smayling,2018,2018,1,<NA>,New,NaN
20,AS-10045,Aaron Smayling,2018,2019,0,1,Sleeping,-158
21,AS-10045,Aaron Smayling,2018,2020,1,0,Returning,48
23,AS-10045,Aaron Smayling,2018,2021,1,1,Consistent,32
30,AB-10060,Adam Bellavance,2019,2019,1,<NA>,New,NaN
31,AB-10060,Adam Bellavance,2019,2020,1,1,Consistent,-34
40,AB-10060,Adam Bellavance,2019,2021,1,1,Consistent,18
48,AH-10075,Adam Hart,2018,2018,1,<NA>,New,NaN
49,AH-10075,Adam Hart,2018,2019,1,1,Consistent,-158
50,AH-10075,Adam Hart,2018,2020,1,1,Consistent,48
56,AH-10075,Adam Hart,2018,2021,1,1,Consistent,32
68,AS-10090,Adam Shillingsburg,2018,2018,1,<NA>,New,NaN
73,AS-10090,Adam Shillingsburg,2018,2019,1,1,Consistent,-158
77,AS-10090,Adam Shillingsburg,2018,2020,1,1,Consistent,48
85,AS-10090,Adam Shillingsburg,2018,2021,1,1,Consistent,32
93,AB-10105,Adrian Barton,2018,2018,1,<NA>,New,NaN
95,AB-10105,Adrian Barton,2018,2019,1,1,Consistent,-158
101,AB-10105,Adrian Barton,2018,2020,1,1,Consistent,48
104,AB-10105,Adrian Barton,2018,2021,1,1,Consistent,32
113,AH-10120,Adrian Hane,2018,2018,1,<NA>,New,NaN
114,AH-10120,Adrian Hane,2018,2019,0,1,Sleeping,-158
115,AH-10120,Adrian Hane,2018,2020,1,0,Returning,48
123,AH-10120,Adrian Hane,2018,2021,1,1,Consistent,32
130,AS-10135,Adrian Shami,2020,2020,1,<NA>,New,NaN
131,AS-10135,Adrian Shami,2020,2021,1,1,Consistent,-6
133,AB-10150,Aimee Bixby,2018,2018,1,<NA>,New,NaN
138,AB-10150,Aimee Bixby,2018,2019,1,1,Consistent,-158
139,AB-10150,Aimee Bixby,2018,2020,1,1,Consistent,48
140,AB-10150,Aimee Bixby,2018,2021,1,1,Consistent,32
145,AB-10165,Alan Barnes,2018,2018,1,<NA>,New,NaN
146,AB-10165,Alan Barnes,2018,2019,1,1,Consistent,-158
152,AB-10165,Alan Barnes,2018,2020,0,1,Sleeping,48

In [189]:
# save df_unique to excel
df_unique.to_excel('Output_forTableau.xlsx', index=False)

In [ ]:
# generate required output dataframe by using df_unique and df_final1
df_final1=df_final1.merge(df_unique, on=['Customer ID','Customer Name','First Purchase Date','Year','Order?','Last Year Order?','Customer Classification'])

In [202]:
df_final1.shape

(10396, 27)

In [201]:
# save df_final1 to excel
df_final1.to_excel('Output_Required.xlsx', index=False)